# Generated by Django 4.2.1 on 2023-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='datee',
            field=models.DateField(null=True),
        ),
    ]
