# Generated by Django 4.2.1 on 2023-05-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
    ]
