# Generated by Django 4.2.1 on 2023-05-22 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created']},
        ),
    ]
